# Workflow name
name: "Lint Checks"

on: pull_request

jobs:
  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn eslint --quiet src
      - run: yarn stylelint ./src/**/*.css
      - run: yarn prettier --check src
      - run: yarn jscpd src
