name: "Semantic Release"

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tiwariav/github-actions/setup-yarn@main
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            .eslintcache
            .stylelintcache
            node_modules/.cache/prettier/.prettier-cache
            tsconfig.build.tsbuildinfo
          key: ${{ runner.os }}-lint-cache-${{ hashFiles('yarn.lock', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-lint-cache-
      - run: ls -al
      - run: yarn eslint --cache --cache-strategy=content --quiet --debug src
      - run: yarn stylelint --cache ./src/**/*.css
      - run: yarn prettier --cache --check src
      - run: yarn jscpd src
      - run: yarn build
      - uses: tiwariav/github-actions/semantic-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
